### ISSUE TITLE
Asteric value of property cors.allowed.origins causes Ignite error

### ISSUE THREAD

**Issue by andreaskring** [aldica/aldica#55]
## BUG

Setting the Alfresco global property `cors.allowed.origins` to the value `*` like this:
```
cors.enabled=true
cors.allowed.origins=*
```
causes an Ignite error during start up of Alfresco. Setting the property to another value, e.g. `cors.allowed.origins=http://xyz` works fine.

### Expected behavior

The aldica-enabled Alfresco repository is expected to start up without errors.

### Actual behavior

The aldica-enabled Alfresco repository throws the following error during start up when `cors.allowed.origins=*`:
```
alfresco_1           |  2020-10-07 12:15:16,869  INFO  [extensions.webscripts.DeclarativeRegistry] [asynchronouslyRefreshedCacheThreadPool1] Registered 0 Schema Description Documents (+0 failed) 
alfresco_1           |  2020-10-07 12:15:17,172  WARN  [scripts.servlet.X509ServletFilterBase] [localhost-startStop-1] clientAuth does not appear to be set for Tomcat. clientAuth must be set to 'want' for X509 Authentication
alfresco_1           |  2020-10-07 12:15:17,172  WARN  [scripts.servlet.X509ServletFilterBase] [localhost-startStop-1] Attempting to set clientAuth=want through JMX...
alfresco_1           |  2020-10-07 12:15:17,194  WARN  [scripts.servlet.X509ServletFilterBase] [localhost-startStop-1] Unable to set clientAuth=want through JMX.
alfresco_1           | 07-Oct-2020 12:15:17.195 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more Filters failed to start. Full details will be found in the appropriate container log file
alfresco_1           | 07-Oct-2020 12:15:17.195 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [/alfresco] startup failed due to previous errors
alfresco_1           |  2020-10-07 12:15:17,243  INFO  [ignite.lifecycle.SpringIgniteLifecycleBean] [localhost-startStop-1] Closing Ignite isntance knrGrid
alfresco_1           |  2020-10-07 12:15:17,319  ERROR [ignite.internal.IgniteKernal%knrGrid] [localhost-startStop-1] Failed to stop component (ignoring): GridProcessorAdapter []
alfresco_1           |  java.lang.UnsupportedOperationException
alfresco_1           | 	at org.jsr166.ConcurrentLinkedHashMap.clear(ConcurrentLinkedHashMap.java:1542)
alfresco_1           | 	at org.apache.ignite.internal.processors.job.GridJobProcessor.stop(GridJobProcessor.java:375)
alfresco_1           | 	at org.apache.ignite.internal.IgniteKernal.stop0(IgniteKernal.java:2627)
alfresco_1           | 	at org.apache.ignite.internal.IgniteKernal.stop(IgniteKernal.java:2499)
alfresco_1           | 	at org.apache.ignite.internal.IgnitionEx$IgniteNamedInstance.stop0(IgnitionEx.java:2650)
alfresco_1           | 	at org.apache.ignite.internal.IgnitionEx$IgniteNamedInstance.stop(IgnitionEx.java:2613)
alfresco_1           | 	at org.apache.ignite.internal.IgnitionEx.stop(IgnitionEx.java:339)
alfresco_1           | 	at org.apache.ignite.Ignition.stop(Ignition.java:223)
alfresco_1           | 	at org.aldica.common.ignite.lifecycle.SpringIgniteLifecycleBean.lambda$shutdownGrid$5(SpringIgniteLifecycleBean.java:160)
alfresco_1           | 	at org.aldica.common.ignite.context.ExternalContext.withExternalContext(ExternalContext.java:112)
alfresco_1           | 	at org.aldica.common.ignite.lifecycle.SpringIgniteLifecycleBean.shutdownGrid(SpringIgniteLifecycleBean.java:154)
alfresco_1           | 	at org.aldica.common.ignite.lifecycle.SpringIgniteLifecycleBean.onApplicationEvent(SpringIgniteLifecycleBean.java:77)
alfresco_1           | 	at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEventInternal(SafeApplicationEventMulticaster.java:221)
alfresco_1           | 	at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEvent(SafeApplicationEventMulticaster.java:191)
alfresco_1           | 	at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEvent(SafeApplicationEventMulticaster.java:206)
alfresco_1           | 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
alfresco_1           | 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
alfresco_1           | 	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1009)
alfresco_1           | 	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:975)
alfresco_1           | 	at org.springframework.web.context.ContextLoader.closeWebApplicationContext(ContextLoader.java:517)
alfresco_1           | 	at org.springframework.web.context.ContextLoaderListener.contextDestroyed(ContextLoaderListener.java:112)
alfresco_1           | 	at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4746)
alfresco_1           | 	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5403)
alfresco_1           | 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
alfresco_1           | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
alfresco_1           | 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
alfresco_1           | 	at org.apache.catalina.core.ContainerBase.access$000(ContainerBase.java:129)
alfresco_1           | 	at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:150)
alfresco_1           | 	at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:140)
alfresco_1           | 	at java.base/java.security.AccessController.doPrivileged(Native Method)
alfresco_1           | 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:717)
alfresco_1           | 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
alfresco_1           | 	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1125)
alfresco_1           | 	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1859)
alfresco_1           | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
alfresco_1           | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
alfresco_1           | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
alfresco_1           | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
alfresco_1           | 	at java.base/java.lang.Thread.run(Thread.java:834)
alfresco_1           | [12:15:17] Ignite node stopped wih ERRORS [name=knrGrid, uptime=00:00:10.406]
alfresco_1           | 2020-10-07 12:15:17,388  INFO  [ignite.lifecycle.SpringIgniteLifecycleBean] [localhost-startStop-1] Closed Ignite instance knrGrid
alfresco_1           |  2020-10-07 12:15:17,427  INFO  [management.subsystems.ChildApplicationContextFactory] [localhost-startStop-1] Stopping 'Replication' subsystem, ID: [Replication, default]
alfresco_1           |  2020-10-07 12:15:17,428  INFO  [management.subsystems.ChildApplicationContextFactory] [localhost-startStop-1] Stopped 'Replication' subsystem, ID: [Replication, default]
```

### Steps to reproduce the behavior

Configure a single aldica-enabled Alfresco 6.2.1-A8 repo with the following aldica/Ignite configuration:
```
    --add-exports=java.base/jdk.internal.misc=ALL-UNNAMED\
    --add-exports=java.base/sun.nio.ch=ALL-UNNAMED\
    --add-exports=java.management/com.sun.jmx.mbeanserver=ALL-UNNAMED\
    --add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED\
    --add-exports=java.base/sun.reflect.generics.reflectiveObjects=ALL-UNNAMED\
    --illegal-access=permit\
    -XX:+UseG1GC\
    -XX:+ParallelRefProcEnabled\
    -XX:+UseStringDeduplication\
    -XX:+ScavengeBeforeFullGC\
    -XX:+DisableExplicitGC\
    -XX:+AlwaysPreTouch\
    -Dfile.encoding=UTF-8\
    -Djava.net.preferIPv4Stack=true\
    -DIGNITE_PERFORMANCE_SUGGESTIONS_DISABLED=true\
    -DIGNITE_QUIET=true\
    -DIGNITE_NO_ASCII=true\
    -DIGNITE_UPDATE_NOTIFIER=false\
    -DIGNITE_JVM_PAUSE_DETECTOR_DISABLED=true\
    -DIGNITE_SKIP_CONFIGURATION_CONSISTENCY_CHECK=true\

    -Daldica.core.name=knrGrid\
    -Daldica.caches.remoteSupport.enabled=true\
```

### Tell us about your environment

The stack is started locally with the following Docker-compose configuration:
```
version: '3.4'
services:
  alfresco:
    image: magentaaps/knr-repo:development
    build:
      dockerfile: docker/Dockerfile.repo
      context: .
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - 8080:8080
      - 8888:8888
    volumes:
      - type: volume
        source: repo-volume
        target: /usr/local/tomcat/alf_data
      - type: bind
        source: ./dev-environment/alfresco-global.properties
        target: /usr/local/tomcat/shared/classes/alfresco-global.properties
      - type: bind
        source: ./dev-environment/dev-log4j.properties
        target: /usr/local/tomcat/shared/classes/alfresco/extension/dev-log4j.properties
      - type: bind
        source: ./dev-environment/disable-webscript-caching-context.xml
        target: /usr/local/tomcat/shared/classes/alfresco/extension/disable-webscript-caching-context.xml
    depends_on:
      - postgres

  postgres:
    image: postgres:11.4
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: postgres-volume
        target: /var/lib/postgresql/data

  postgres-keycloak:
    image: postgres
    ports:
      - 5431:5432
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - type: volume
        source: knr-postgres-keycloak-volume
        target: /var/lib/postgresql/data

  keycloak:
    depends_on:
      - postgres-keycloak
    image: quay.io/keycloak/keycloak:11.0.2
    command: [ "-Djboss.socket.binding.port-offset=200", "-Dkeycloak.migration.strategy=IGNORE_EXISTING" ]
    ports:
      - 8280:8280
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-develop.json
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      DB_ADDR: postgres-keycloak
    volumes:
      - type: volume
        source: knr-keycloak-volume
        target: /opt/jboss/keycloak/standalone/data
      - type: bind
        source: ./dev-environment/realm-develop.json
        target: /tmp/realm-develop.json

volumes:
  repo-volume:
  postgres-volume:
  knr-postgres-keycloak-volume:
  knr-keycloak-volume:
```
